# Generated by Django 4.2 on 2023-04-10 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_blog', '0003_comment_delete_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content_area',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
