# Generated by Django 4.2 on 2023-04-27 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_blog', '0006_rename_created_date_comment_created_comment_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
