# Generated by Django 4.2 on 2023-06-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_blog', '0007_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='images.jpg', upload_to='images/'),
        ),
    ]
